import { Question } from "../shared/Activity.types";
import Activity from "../shared/Activity";
import expressionsJson from "./expressions.json";

const expressions: Question[] = expressionsJson

const options: string[] = [
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing",
    "The decision has been made",
    "To master something",
    "To have a bone to pick with someone",
    "The truth is revealed",
    "They get along very well",
    "That’s not my responsibility",
    "To lose the overview",
    "To disappoint someone",
    "To wait and see",
    "A fuss about nothing"
]

const getOptions = (correctAnswer: string): string[] => {

    const retrievedOptions: string[] = []

    // Get three random options
    while (retrievedOptions.length < 3) {
        const randomIndex = Math.floor(Math.random() * options.length);
        const randomOption = options[randomIndex]

        if (randomOption !== correctAnswer &&
            !retrievedOptions.includes(randomOption)) {
            retrievedOptions.push(randomOption)
        }
    }

    // Put the correct answer at a random spot
    const randomIndex = Math.random() * 4
    retrievedOptions.splice(randomIndex, 0, correctAnswer)

    return retrievedOptions
}


const Expressions = () =>     
    <Activity
        questions={expressions}
        questionKey='expressionsQuestionKey'
        orderingKey='expressionsOrderingKey'
        getOptions={getOptions}
    />


export default Expressions
